//  Created by applechang on 2017/5/13.

#ifndef GLIVE_AV_MACRO_H__
#define GLIVE_AV_MACRO_H__

#define QAV_AUTH_BITS_AUDIENCE QAV_AUTH_BITS_CREATE_ROOM|QAV_AUTH_BITS_JOIN_ROOM|QAV_AUTH_BITS_RECV_AUDIO|QAV_AUTH_BITS_RECV_VIDEO|QAV_AUTH_BITS_RECV_SUB

#define MAXSCALE 2.0 //最大缩放比例
#define MINSCALE 0.5 //最小缩放比例

#endif /* GLIVE_AV_MACRO_H__ */
