// Generated by the btprotoc v_0.4 on 2017-09-20.  DO NOT EDIT!
// source: commProtocol.proto

#ifndef commProtocol_pb_h
#define commProtocol_pb_h

//ENUM NETWORK_TYPE
typedef NS_ENUM(NSInteger, PB_NETWORK_TYPE){
    OD_UNKNOWN    = -1,	
    OD_wire    = 0,	
    OD_wifi    = 1,	
    OD_G2    = 2,	
    OD_G3    = 3,	
    OD_G4    = 4,	

};

//ENUM AUTH_TYPE
typedef NS_ENUM(NSInteger, PB_AUTH_TYPE){
    OD_PT    = 0,	
    OD_QQCON    = 1,	
    OD_WX    = 2,	
    OD_QQ    = 3,	// QQ skey

};

//ENUM CLIENT_TYPE
typedef NS_ENUM(NSInteger, PB_CLIENT_TYPE){
    OD_PC    = 1,	
    OD_ANDROID    = 2,	
    OD_IOS    = 3,	
    OD_QQ_PC    = 4,	
    OD_QQ_IOS    = 5,	
    OD_QQ_ANDROID    = 6,	

};

//Message commRequest
typedef NS_ENUM(NSInteger, PB_commRequest){
    tencent_im_bj_commRequest_version	= 1,	//版本号
    tencent_im_bj_commRequest_app_name	= 2,	//业务名称
    tencent_im_bj_commRequest_cmd	= 3,	//请求命令字
    tencent_im_bj_commRequest_seq	= 4,	//请求序列号
    tencent_im_bj_commRequest_client_ip	= 5,	//用户客户端ip
    tencent_im_bj_commRequest_service_ip	= 6,	//请求服务端ip
    tencent_im_bj_commRequest_business	= 7,	//调用方
    tencent_im_bj_commRequest_auth_key	= 8,	//鉴权key
    tencent_im_bj_commRequest_auth_type	= 9,	//鉴权类型
    tencent_im_bj_commRequest_auth_ip	= 10,	//调用方ip
    tencent_im_bj_commRequest_auth_appid	= 11,	//appid
    tencent_im_bj_commRequest_uid	= 12,	//用户唯一标示
    tencent_im_bj_commRequest_uin	= 13,	//qq用户uin
    tencent_im_bj_commRequest_openid	= 14,	//第三方授权用户openid
    tencent_im_bj_commRequest_body	= 15,	//body
    tencent_im_bj_commRequest_microtime	= 16,	// 请求时的微秒时刻
    tencent_im_bj_commRequest_client_type	= 17,	// 客户端类型
    tencent_im_bj_commRequest_client_release	= 18,	// 客户端release
    tencent_im_bj_commRequest_user_sig	= 19,	// 齐齐交友专用，音视频 user_sig
    tencent_im_bj_commRequest_network	= 20,	// 网络状况
    tencent_im_bj_commRequest_from_id	= 21,	// 本次拉起交友业务的来源id\参数不存在时，记为空
    tencent_im_bj_commRequest_hy_client_type	= 100,	// 花样客户端类型

};

//Message commResponse
typedef NS_ENUM(NSInteger, PB_commResponse){
    tencent_im_bj_commResponse_seq	= 1,	//请求序列号
    tencent_im_bj_commResponse_code	= 2,	//错误码
    tencent_im_bj_commResponse_msg	= 3,	//错误信息
    tencent_im_bj_commResponse_body	= 4,	//body

};



#endif /* commProtocol_pb_h */
